server:
    port: 8080
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: password
        url: jdbc:h2:mem:testdb
        username: sa
    jpa:
        database: H2
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: true
        show-sql: true
    liquibase:
        enabled: false
    main:
        allow-bean-definition-overriding: true
    h2:
        console:
            enabled: true
springfox:
    documentation:
        swagger:
            v2:
                path: /api-docs
